#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
vmware-user-suid-wrapper &
/usr/bin/feh --bg-fill /opt/image/fondo.jpg &
~/.config/polybar/./launch.sh &
picom &
bspc config border_width 0
wmname LG3D &


#include <vcl.h>
#pragma hdrstop

#include "Unit4.h"
//---------------------------------------------------------------------------
#pragma package(smart_init)
#pragma resource "*.dfm"
TForm4 *Form4;
//---------------------------------------------------------------------------
__fastcall TForm4::TForm4(TComponent* Owner)
	: TForm(Owner)
{ //in=>solo lectura
 //out=>solo escritura(creacion)
 //App=>escritura(al final del archivo)
 //IN|OUT=>lectura y escritura(NO creacion)
}
//---------------------------------------------------------------------------
void __fastcall TForm4::Button1Click(TObject *Sender)
{
Edit1->Text="0";
Edit2->Text="";
Edit3->Text="";
Edit4->Text="1";
Edit5->Text="1";
Edit6->Text="2000";
}
//---------------------------------------------------------------------------
void __fastcall TForm4::FormCreate(TObject *Sender)
{  ruta="C:\\Users\\Usuario G\\Desktop\\INF210\\Datos\\";
	nom="Alumnos.dat";
	AnsiString nomArch=ruta+nom;
	fstream f(nomArch.c_str(),ios::binary|ios::in);  //lectura
	 if (f.fail()) {
	   f.open(nomArch.c_str(),ios::binary|ios::out); //se crea el archivo
	 }
	 f.close();
}
//---------------------------------------------------------------------------
void __fastcall TForm4::Button2Click(TObject *Sender)
{ RegAlumno reg; AnsiString nomArch=ruta+nom;
  AnsiString aux;
  reg.cod = StrToInt(Edit1->Text);
  aux=Edit2->Text;
  strcpy(reg.nom,aux.c_str());
  aux=Edit3->Text;
  strcpy(reg.dir,aux.c_str());
  reg.fecha.dia=StrToInt(Edit4->Text);
  reg.fecha.mes=StrToInt(Edit5->Text);
  reg.fecha.año=StrToInt(Edit6->Text);

  fstream f(nomArch.c_str(),ios::binary|ios::app);
  f.write((char*)&reg,sizeof(reg));//ahora guarda  todo completo por "sizeof"
  f.close();
  Button1Click(Sender);//limpiar pantalla
  ShowMessage("Datos guardados");

}
//---------------------------------------------------------------------------
void __fastcall TForm4::Button3Click(TObject *Sender)
{  AnsiString nomArch=ruta+nom;
   AnsiString cad="";
   RegAlumno reg;
  /* fstream f(nomArch.c_str(),ios::binary|ios::in);
   f.read((char*)&reg,23);
   Edit1->Text=reg.cod;
   Edit2->Text=reg.nom;
   ShowMessage("SIG");
   f.read((char*)&reg,23);
   Edit1->Text=reg.cod;
   Edit2->Text=reg.nom;   */
  /* for (byte i=1; i < 23; i++) {
	 f.read((char*)&x,1)
	 cad=cad+IntToStr(x)+",";

   }
   f.close();                   */
}
//----
